[[redirects]]
  from = "/improve-g2-rank/"
  to = "/blog/improve-g2-rank/"

[[redirects]]
  from = "/articles/improve-g2-rankings/"
  to = "/blog/improve-g2-rank/"

[[redirects]]
  from = "/faq"
  to = "/" 

[[redirects]]
  from = "/blog/index.html"
  to = "/blog/" 

[[redirects]]
  from = "/custom-categorize-aerial-imagery-api/"
  to = "/"   

[[redirects]]
  from = "/machine-learning-functions-as-a-service/"
  to = "/"  

[[redirects]]
  from = "/text-classification-api/"
  to = "/products/text-classification-api/"  

[[redirects]]
  from = "/computer-vision-api"
  to = "/products//computer-vision-api/"      

[[redirects]]
  from = "/image-classification-api/"
  to = "/products/image-classification-api/"  

[[redirects]]
  from = "/product/"
  to = "/products/"

[[redirects]]
  from = "/semantic-image-search"
  to = "/products/semantic-image-search"

[[redirects]]
  from = "/migrating-from-monkey-learn"
  to = "/products/migrating-from-monkey-learn"

[[redirects]]
  from = "/custom-content-moderation-api"
  to = "/products/custom-content-moderation-api"

[[redirects]]
  from = "/semantic-text-search"
  to = "/products/semantic-text-search"

[[redirects]]
  from = "/ai-for-digital-asset-management"
  to = "/products/ai-for-digital-asset-management"
