# General Settings
title: "Nyckel"
email: "feedback@nyckel.com"
email_2: "feedback@nyckel.com"
image: "/assets/images/important/nyckel-cover.webp"
description: "Use AI to easily classify text and images."
black_logo_1x: "/assets/images/important/Nyckel-Logo-Color-180.webp"
black_logo_2x: "/assets/images/important/Nyckel-Logo-Color-350.webp"
light_logo_1x: "/assets/images/important/Nyckel-Logo-White-180.webp"
light_logo_2x: "/assets/images/important/Nyckel-Logo-White-350.webp"
favicon_1x: "/favicon.png"
favicon_2x: "/favicon.png"

address_01: '01 Silver Terrace Waterville Maine'
phone_number: "+01 (434) 444 2268"
copyright_text: "© 2023 Nyckel"

#google_map: |
#  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "https://github.com/nyckelai"
      icon: "jam jam-github"
      alt: "Nyckel on Github"
      
    - url: "https://www.youtube.com/@nyckelai"
      icon: "jam jam-youtube"
      alt: "Nyckel on YouTube"

    - url: "https://www.linkedin.com/company/nyckelai/"
      icon: "jam jam-linkedin"
      alt: "Nyckel on LinkedIn"

external_links:
  title: "Learn More"
  links:
    - url: "/pricing/"
      text: "Pricing"
    - url: "/public-functions/"
      text: "Pre-Trained Models"  
    - url: "/customers/"
      text: "Customers"    

external_links_02:
  title: "Get Started"
  links:
    - url: "/contact/"
      text: "Talk to Sales"
    - url: "https://www.nyckel.com/console"
      text: "Sign Up"

external_links_04:
  title: "Developers"
  links:
    - url: "https://www.nyckel.com/docs"
      text: "API Docs"
    - url: "https://status.nyckel.com/"
      text: "API Status"               

external_links_03:
  title: "Company"
  links:
    - url: "/about/"
      text: "About"
    - url: "/blog/"
      text: "Blog"   
    - url: "mailto:feedback@nyckel.com"
      text: "Support" 

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"